apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-crd-upgrader-job-k8ssandra
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "10"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels: {{ include "k8ssandra.labels" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}-crd-upgrader-k8ssandra
      containers:
        - name: crd-upgrade-job-k8ssandra
          image: {{ .Values.client.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - -upgradecrds
            - --targetVersion
            - {{ .Chart.Version }}
