apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-crd-upgrader-k8ssandra
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - cassandra.datastax.com
    resources:
      - cassandradatacenters
    verbs:
      - get
      - list
      - delete
      - watch
      - update
      - create
      - patch
  - apiGroups:
      - reaper.cassandra-reaper.io
    resources:
      - reapers
    verbs:
      - get
      - list
      - delete
      - watch
      - update
      - create
      - patch
