{{- if not .Values.cleaner.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-crd-upgrader-k8ssandra
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
{{- end }}
