{{- if .Values.clusterWideInstall }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- else }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Values.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
