{{- $traefik := .Values.ingress.traefik -}}
{{- if $traefik.enabled }}
{{- $releaseName := .Release.Name -}}
{{- $datacenterName := include "k8ssandra.datacenterName" . -}}

{{- if $traefik.stargate.enabled }}
{{- if and $traefik.stargate.cassandra.enabled $traefik.cassandra.enabled }}
  {{- fail "ingress.traefik.stargate.cassandra.enabled and ingress.traefik.cassandra.enabled cannot both be enabled." }}
{{- end }}
{{- $stargateHost := required "Values.ingress.traefik.stargate.host is required" $traefik.stargate.host }}
{{- if $traefik.stargate.cassandra.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $releaseName }}-{{ $datacenterName }}-stargate
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  entryPoints:
  {{- range $traefik.stargate.cassandra.entrypoints }}
  - {{ . }}
  {{- end }}
  routes:
    - match: HostSNI(`{{ $stargateHost }}`)
      services:
        - name: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
          kind: Service
          port: 9042
{{- end }}
{{- end }}
{{- end }}
