{{- define "k8ssandra.datacenterSize" -}}
  {{ (index .Values.cassandra.datacenters 0).size }}
{{- end }}
{{- $stargateIngress := .Values.stargate.ingress -}}
{{- if $stargateIngress.enabled }}

{{- if and .Values.ingress.traefik.cassandra.enabled $stargateIngress.cassandra.enabled }}
  {{- fail "stargate.ingress.cassandra.enabled and ingress.traefik.cassandra.enabled cannot both be enabled." }}
{{- end }}

{{- $releaseName := .Release.Name -}}
{{- $datacenterName := include "k8ssandra.datacenterName" . -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: k8ssandra-stargate
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  rules:
{{- if $stargateIngress.auth.enabled }}
{{- $stargateAuthHost := include "k8ssandra.stargateIngressAuthHost" . }}
    - http:
        paths:
          - path: /v1/auth
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8081

  {{- if $stargateAuthHost }}
      host: "{{ $stargateAuthHost }}"
  {{- end }}
{{- end }}
{{- if $stargateIngress.graphql.enabled }}
{{- $stargateGraphqlHost := include "k8ssandra.stargateIngressGraphqlHost" . }}
    - http:
        paths:
          - path: /graphql-schema
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8080
          - path: /graphql/
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8080
  {{- if $stargateIngress.graphql.playground.enabled }}
          - path: /playground
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8080
  {{- end }}
  {{- if $stargateGraphqlHost }}
      host: "{{ $stargateGraphqlHost }}"
  {{- end }}
{{- end }}
{{- if $stargateIngress.rest.enabled }}
{{- $stargateRestHost := include "k8ssandra.stargateIngressRestHost" . }}
    - http:
        paths:
          - path: /v2/
            backend:
              serviceName: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
              servicePort: 8082
  {{- if $stargateRestHost }}
      host: "{{ $stargateRestHost }}"
  {{- end }}
{{- end }}
{{- end }}
