{{- if and .Values.repair.reaper.enabled .Values.repair.reaper.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-reaper-operator-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-reaper-operator-k8ssandra
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-reaper-operator-k8ssandra
    spec:
      serviceAccountName: {{ .Release.Name }}-reaper-operator-k8ssandra
      containers:
        - args:
          - --enable-leader-election
          command:
            - /manager
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: docker.io/thelastpickle/reaper-operator
          name: reaper-operator
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
{{- end }}