{{- if and .Values.repair.reaper.enabled .Values.repair.reaper.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-reaper-operator-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
{{- end }}