#!/usr/bin/env bash
echo "CT_VERSION=v3.14.0" >> $GITHUB_ENV
echo "HELM_UNITTEST_VERSION=v1.0.3" >> $GITHUB_ENV
echo "CERT_MANAGER_VERSION=v1.19.2" >> $GITHUB_ENV
echo "YQ_VERSION=v4.52.4" >> $GITHUB_ENV
