{{- if and .Values.cassandra.auth.enabled .Values.reaper.enabled (not .Values.reaper.cassandraUser.secret) }}
  {{- $defaultUsername := "reaper" }}
  {{- $overrideUsername := .Values.reaper.cassandraUser.username }}
  {{- $secretUsername := "" }}
  {{- $username := "" }}

  {{- $randomPassword := (include "k8ssandra.password" .) }}
  {{- $secretPassword := "" }}
  {{- $password := "" }}

  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "k8ssandra.reaperUserSecretName" .)) }}
  {{- if $secret }}
    {{- $secretUsername = index $secret.data "username" | b64dec }}
    {{- $secretPassword = index $secret.data "password" | b64dec }}
  {{- end }}

  {{- if $overrideUsername }}
    {{- if (eq $overrideUsername $secretUsername) }}
      {{- $username = $secretUsername }}
      {{- $password = $secretPassword }}
    {{- else }}
      {{- $username = $overrideUsername }}
      {{- $password = $randomPassword }}
    {{- end }}
  {{- else if $secret }}
    {{- $username = $secretUsername }}
    {{- $password = $secretPassword }}
  {{- else }}
    {{- $username = $defaultUsername }}
    {{- $password = $randomPassword }}
  {{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8ssandra.reaperUserSecretName" . }}
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
{{- end }}
