chart-dirs:
  - charts
target-branch: main
check-version-increment: false
validate-maintainers: false
excluded-charts:
  - backup
  - k8ssandra
  - k8ssandra-common
  - medusa-operator
  - reaper-operator
  - restore
