{{- if .Values.backupRestore.medusa.enabled }}
{{- if and .Values.cassandra.auth.enabled (not .Values.backupRestore.medusa.cassandraUser.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cassandra.clusterName }}-medusa
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
type: Opaque
data:
  username: {{ (default "medusa" .Values.backupRestore.medusa.cassandraUser.username) | b64enc | quote }}
  password: {{ include "k8ssandra-common.password" . }}
{{- end }}
{{- end }}
