{{- $cassIngress := .Values.cassandra.ingress -}}
{{- $stargateIngress := .Values.stargate.ingress.cassandra -}}
{{- if $cassIngress.enabled }}
{{- $releaseName := .Release.Name -}}
{{- $datacenterName := include "k8ssandra.datacenterName" . -}}
{{- $cassIngressHost := default "*" $cassIngress.host }}

{{- if and $stargateIngress.enabled $cassIngress.enabled }}
  {{- fail "stargate.ingress.cassandra.enabled and cassandra.ingress.enabled cannot both be true." }}
{{- end }}
{{- if eq $cassIngress.method "traefik" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $releaseName }}-k8ssandra-cassandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  entryPoints:
    - {{ $cassIngress.traefik.entrypoint }}
  routes:
    - match: HostSNI(`{{ $cassIngressHost }}`)
      services:
        - name: {{ include "k8ssandra.clusterName" . }}-{{ $datacenterName }}-service
          port: 9042
{{- end }}
{{- end }}
