{{- if .Values.repair.reaper.enabled }}
apiVersion: reaper.cassandra-reaper.io/v1alpha1
kind: Reaper
metadata:
  name: {{ .Release.Name }}-reaper-k8ssandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  image: thelastpickle/cassandra-reaper:2.1.3
  serverConfig:
    {{- if .Values.repair.reaper.autoschedule }}
    autoScheduling:
      enabled: {{ .Values.repair.reaper.autoschedule }}
    {{- end}}
    storageType: cassandra
    jmxUserSecretName: {{ .Release.Name }}-reaper-secret-k8ssandra
    cassandraBackend:
      cassandraDatacenter:
        name: {{ (index .Values.cassandra.datacenters 0).name }}
      replication:
        networkTopologyStrategy:
          {{ (index .Values.cassandra.datacenters 0).name }}: {{ min (index .Values.cassandra.datacenters 0).size 3}}
{{- end }}