{{- if not .Values.cleaner.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cleaner-k8ssandra
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
{{- end }}
