baseURL = "https://docs-staging-v1.k8ssandra.io/"
url_latest_version = "https://docs-staging-v1.k8ssandra.io"

[[params.versions]]
  version = "Common"
  fullversion = "k8ssandra-operator"
  githubbranch = "docs"
  url = "https://docs-staging.k8ssandra.io"

[[params.versions]]
  version = "v1"
  fullversion = "k8ssandra-v1 (deprecated)"
  githubbranch = "docs-v1"
  url = "https://docs-staging-v1.k8ssandra.io"

