apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-leader
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8ssandra-common.fullname" . }}-leader
subjects:
  - kind: ServiceAccount
    name: {{ include "k8ssandra-common.fullname" . }}
