{{- $webhooks := .Values.admissionWebhooks.enabled -}}
{{- $manageWebhookCertificate := and $webhooks (not .Values.admissionWebhooks.certificateSecret) -}}
{{- $metricsPort := regexFind "(?:)(\\d*)$" .Values.metrics.address -}}
{{- $metricsEnabled := not (eq "0" $metricsPort) -}}
{{- $metricsTLSEnabled := and $metricsEnabled (.Values.metrics.tls.enabled | default false) -}}
{{- $selfSignedCertificates := or $manageWebhookCertificate $metricsTLSEnabled -}}

{{ if $selfSignedCertificates }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-selfsigned-issuer
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  {{- with include "k8ssandra-common.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selfSigned: {}
{{- if $manageWebhookCertificate }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-serving-cert
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  {{- with include "k8ssandra-common.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  dnsNames:
    -  {{ include "k8ssandra-common.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    -  {{ include "k8ssandra-common.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "k8ssandra-common.fullname" . }}-selfsigned-issuer
  secretName: {{ include "cass-operator.webhookCertificateSecret" . }}
{{- end }}
{{- if $metricsTLSEnabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-metrics-cert
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  {{- with include "k8ssandra-common.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  dnsNames:
    -  {{ include "k8ssandra-common.fullname" . }}-metrics-service.{{ .Release.Namespace }}.svc
    -  {{ include "k8ssandra-common.fullname" . }}-metrics-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "k8ssandra-common.fullname" . }}-selfsigned-issuer
  secretName: {{ include "k8ssandra-common.fullname" . }}-metrics-server-cert
{{- end }}
{{ end }}
