kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cass-operator.fullname" . }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ template "cass-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "cass-operator.fullname" . }}-cr
  apiGroup: rbac.authorization.k8s.io
