kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8ssandra-common.fullname" . }}-cr
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8ssandra-common.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "k8ssandra-common.fullname" . }}-cr
  apiGroup: rbac.authorization.k8s.io
