apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "k8ssandra-common.fullname" . }}-cr
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
