{{- if .Values.global.clusterScopedResources }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8ssandra-common.fullname" . }}
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  {{- with include "k8ssandra-common.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8ssandra-common.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "k8ssandra-common.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end}}
---
{{- if not .Values.global.clusterScoped }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "k8ssandra-common.fullname" . }}
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  {{- with include "k8ssandra-common.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8ssandra-common.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "k8ssandra-common.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
