{{- if .Values.clusterScoped }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cass-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cass-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "cass-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  {{- else }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cass-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cass-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "cass-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
