baseURL = "http://localhost:1313/"
url_latest_version = "http://localhost:1313/"

[[params.versions]]
  version = "k8ssandra-operator (current)"
  fullversion = "k8ssandra-operator"
  githubbranch = "docs"
  url = "http://localhost:1313"

[[params.versions]]
  version = "K8ssandra v1 (deprecated)"
  fullversion = "k8ssandra-v1"
  githubbranch = "docs-v1"
  url = "http://localhost:1313"