baseURL = "http://localhost:1313/"
url_latest_version = "http://localhost:1313/"

[[params.versions]]
  version = "Common"
  fullversion = "Common Information"
  githubbranch = "docs"
  url = "http://localhost:1313"

[[params.versions]]
  version = "v1"
  fullversion = "k8ssandra-v1"
  githubbranch = "docs-v1"
  url = "http://localhost:1313"

[[params.versions]]
  version = "v2"
  fullversion = "k8ssandra-operator-v1"
  githubbranch = "docs-v2"
  url = "http://localhost:1313"