{{- if .Values.repair.reaper.enabled }}
apiVersion: reaper.cassandra-reaper.io/v1alpha1
kind: Reaper
metadata:
  name: {{ .Release.Name }}-reaper-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  image: thelastpickle/cassandra-reaper:2.0.5
  serverConfig:
    storageType: cassandra
    jmxUserSecretName: {{ .Release.Name }}-reaper-secret-k8ssandra
    cassandraBackend:
      clusterName: {{ .Values.clusterName }}
      replication:
        networkTopologyStrategy:
          {{ .Values.datacenterName }}: {{ min .Values.size 3}}
      # This is a bit of a hack. We really should not be specifying the service name here as it is
      # implementation detail of cass-operator. reaper-operator needs to be updated to simply take
      # the name of the CassandraDatacenter here.
      cassandraService: {{ .Values.clusterName }}-{{ .Values.datacenterName }}-service
{{- end }}