{{- if .Values.repair.reaper.enabled }}
apiVersion: reaper.cassandra-reaper.io/v1alpha1
kind: Reaper
metadata:
  name: {{ .Release.Name }}-reaper-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  image: thelastpickle/cassandra-reaper:2.0.5
  serverConfig:
    {{- if .Values.repair.reaper.autoschedule }}
    autoScheduling:
      enabled: {{ .Values.repair.reaper.autoschedule }}
    {{- end}}
    storageType: cassandra
    jmxUserSecretName: {{ .Release.Name }}-reaper-secret-k8ssandra
    cassandraBackend:
      cassandraDatacenter:
        name: {{ .Values.datacenterName }}
      replication:
        networkTopologyStrategy:
          {{ .Values.datacenterName }}: {{ min .Values.size 3}}
{{- end }}