global:
  # -- Determines whether k8ssandra-operator only watch and manages
  # K8ssandraCluster in the same namespace in which the operator is deployed
  # or if watches and manages K8ssandraClusters across all namespaces.
  clusterScoped: false
# -- A name in place of the chart name which is used in the metadata.name of
# objects created by this chart.
nameOverride: ''
# -- A name in place of the value used for metadata.name in objects created by
# this chart. The default value has the form releaseName-chartName.
fullnameOverride: ''
# -- Labels to be added to all deployed resources.
commonLabels: {}
# -- Sets the number of k8ssandra-operator pods.
replicaCount: 1
# -- Determines if the k8ssandra-operator should be installed as the control plane
# or if it's simply in a secondary cluster waiting to be promoted
controlPlane: true
# Sets properties for the k8ssandra-operator container
image:
  # -- Container registry containing the repository where the image resides
  registry: docker.io
  # -- Docker repository for cass-operator
  repository: k8ssandra/k8ssandra-operator
  # -- Pull policy for the operator container
  pullPolicy: IfNotPresent
  # -- Tag of the k8ssandra-operator image to pull from image.repository
  tag: v1.2.0
  # -- Docker registry containing all cass-operator related images. Setting this
  # allows for usage of an internal registry without specifying serverImage,
  # configBuilderImage, and busyboxImage on all CassandraDatacenter objects.
  registryOverride:
# -- References to secrets to use when pulling images. See:
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
serviceAccount:
  # -- Annotations to add to the service account.
  annotations: {}
# -- Annotations for the cass-operator pod.
podAnnotations: {}
# -- PodSecurityContext for the cass-operator pod. See:
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext: {}
securityContext:
  # -- Run cass-operator container as non-root user
  runAsNonRoot: true
  # -- Group for the user running the k8ssandra-operator container / process
  runAsGroup: 65534
  # -- User for running the k8ssandra-operator container / process
  runAsUser: 65534
# -- Resources requests and limits for the cass-operator pod. We usually
# recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments
# with little resources, such as Minikube. If you want to specify resources, add
# `requests` and `limits` for `cpu` and `memory` while removing the existing
# `{}`
resources: {}

# -- The cleaner is a pre-delete hook that that ensures objects with finalizers
# get deleted. For example, cass-operator sets a finalizer on the
# CassandraDatacenter. Kubernetes blocks deletion of an object until all of its
# finalizers are cleared. In the case of the CassandraDatacenter object,
# cass-operator removes the finalizer. The problem is that there are no
# ordering guarantees with helm uninstall which means that the cass-operator
# deployment could be deleted before the CassandraDatacenter. The cleaner
# ensures that the CassandraDatacenter is deleted before cass-operator.
cleaner:
  # -- Uncomment to specify the name of the service account to use for the
  # cleaner. Defaults to <release-name>-cleaner-k8ssandra
  # serviceAccount:
  image:
    # -- Image registry for the cleaner
    registry: docker.io
    # -- Image repository for the cleaner
    repository: k8ssandra/k8ssandra-tools
    # -- Tag of the cleaner image to pull from
    tag: latest
    # -- Pull policy for the cleaner container
    pullPolicy: IfNotPresent
# -- k8ssandra-client provides CLI utilities, but also certain functions such as
# upgradecrds that allow modifying the running instances
client:
  # -- Uncomment to specify the name of the service account to use for the
  # client tools image. Defaults to <release-name>-crd-upgrader-k8ssandra.
  # serviceAccount:
  image:
    # -- Image registry for the client
    registry: docker.io
    # -- Image repository for the client
    repository: k8ssandra/k8ssandra-tools
    # -- Tag of the client image to pull from
    tag: latest
    # -- Pull policy for the client container
    pullPolicy: IfNotPresent
