{{- if and .Values.cassandra.auth.enabled (not .Values.reaper.cassandraUser.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8ssandra.clusterName" . }}-reaper
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
type: Opaque
data:
  username: {{ (default "reaper" .Values.reaper.cassandraUser.username) | b64enc | quote }}
  password: {{ include "k8ssandra-common.password" . }}
{{- end }}
