baseURL = "https://docs-v1.k8ssandra.io/"
url_latest_version = "https://docs-v1.k8ssandra.io"

[[params.versions]]
  version = "K8ssandra v1 (deprecated)"
  fullversion = "k8ssandra-v1"
  githubbranch = "docs-v1"
  url = "https://docs-v1.k8ssandra.io"


