baseURL = "https://docs-v1.k8ssandra.io/"
url_latest_version = "https://docs-v1.k8ssandra.io"

[[params.versions]]
  version = "Common"
  fullversion = "k8ssandra-operator"
  githubbranch = "docs"
  url = "https://docs-temp.k8ssandra.io"

[[params.versions]]
  version = "v1"
  fullversion = "K8ssandra v1 (deprecated)"
  githubbranch = "docs-v1"
  url = "https://docs-v1.k8ssandra.io"


