{
 "title": "Stargate",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "4xx Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "restapi_io_dropwizard_jetty_MutableServletContextHandler_percent_4xx_1m",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "restapi_io_dropwizard_jetty_MutableServletContextHandler_percent_5xx_1m",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(restapi_io_dropwizard_jetty_MutableServletContextHandler_requests_count[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_heap_used", "legendFormat": "{{pod}} Usage" },
    { "expr": "jvm_memory_heap_max", "legendFormat": "{{pod}} Max" }
   ]
  }
 ]
}