apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  namespace: prometheus
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus.prometheus.svc.cluster.local:9090
      access: proxy
      isDefault: false
      jsonData:
        timeInterval: 30s