apiVersion: v2
name: backup
description: |
  Creates a CassandraBackup custom resource instance. This chart should be used in conjunction with the Medusa Operator chart.
type: application
version: 0.26.0
home: https://k8ssandra.io/
sources:
  - https://github.com/k8ssandra/medusa-operator
  - https://github.com/k8ssandra/k8ssandra/tree/main/charts/backup
maintainers:
  - name: K8ssandra Team
    email: k8ssandra-developers@googlegroups.com
    url: https://github.com/k8ssandra
deprecated: false
