{{- $stargate := .Values.stargate -}}
{{- if $stargate.enabled }}
  {{- $stargateIngress := $stargate.ingress -}}
  {{- if $stargateIngress.enabled }}
    {{- $stargateCassIngress := $stargateIngress.cassandra -}}
    {{- if $stargateCassIngress.enabled }}

      {{- $cassIngress := .Values.cassandra.ingress -}}
      {{- if $cassIngress.enabled }}
        {{- fail "stargate.ingress.cassandra.enabled and cassandra.ingress.enabled cannot both be true." }}
      {{- end }}

      {{- if eq $stargateCassIngress.method "traefik" }}
        {{- $releaseName := .Release.Name -}}
        {{- $datacenterName := include "k8ssandra.datacenterName" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $releaseName }}-{{ $datacenterName }}-stargate
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  entryPoints:
    - {{ $stargateCassIngress.traefik.entrypoint }}
  routes:
    - match: HostSNI(`{{ default "*" (include "k8ssandra.stargateIngressCassandraHost" .) }}`)
      services:
        - name: {{ $releaseName }}-{{ $datacenterName }}-stargate-service
          port: 9042
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
