apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-crd-upgrader-job-k8ssandra
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "10"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels: {{ include "k8ssandra-common.labels" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "k8ssandra-common.fullname" . }}-crd-upgrader-k8ssandra
      containers:
        - name: crd-upgrade-job-k8ssandra
          image: {{ include "k8ssandra-common.flattenedImage" .Values.client.image }}
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - -upgradecrds
            - --targetVersion
            - {{ .Chart.Version }}
            - --chartName
            - {{ .Chart.Name }}
