{{- if .Values.backupRestore.medusa.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-medusa-operator-k8ssandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-medusa-operator-k8ssandra
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-medusa-operator-k8ssandra
    spec:
      serviceAccountName: {{ .Release.Name }}-medusa-operator-k8ssandra
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        #
        image: docker.io/k8ssandra/medusa-operator:1aa019ee841e
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
{{- end }}
