{{- if .Values.backupRestore.medusa.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-medusa-operator-lead-election-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-medusa-operator-leader-election-k8ssandra
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-medusa-operator-k8ssandra
{{- end }}
