{{- if .Values.backupRestore.medusa.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-medusa-operator-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cassandra.datastax.com
  resources:
  - cassandradatacenters
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrabackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrabackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrarebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrarestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cassandra.k8ssandra.io
  resources:
  - cassandrarestores/status
  verbs:
  - get
  - patch
  - update
{{- end }}
