apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-k8ssandra-operator
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
    control-plane: k8ssandra-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8ssandra-common.selectorLabels" . | nindent 6 }}
      control-plane: k8ssandra-operator
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "k8ssandra-common.labels" . | indent 8 }}
        control-plane: k8ssandra-operator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8ssandra-common.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - command:
        - /manager
        # args:
        # - --config=controller_manager_config.yaml
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8SSANDRA_CONTROL_PLANE
          value: {{ .Values.controlPlane }}
        image: {{ include "k8ssandra-common.flattenedImage" .Values.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: k8ssandra-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /controller_manager_config.yaml
          name: manager-config
          subPath: controller_manager_config.yaml
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: {{ include "k8ssandra-common.fullname" . }}-manager-config
        name: manager-config
