apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-k8ssandra-operator
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cassandra.datastax.com
    resources:
      - cassandradatacenters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - config.k8ssandra.io
    resources:
      - clientconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8ssandra.io
    resources:
      - clientconfigs
      - k8ssandraclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8ssandra.io
    resources:
      - k8ssandraclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - k8ssandra.io
    resources:
      - k8ssandraclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - replication.k8ssandra.io
    resources:
      - replicatedsecrets
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - replication.k8ssandra.io
    resources:
      - replicatedsecrets/finalizers
    verbs:
      - update
  - apiGroups:
      - replication.k8ssandra.io
    resources:
      - replicatedsecrets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - stargate.k8ssandra.io
    resources:
      - stargates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - stargate.k8ssandra.io
    resources:
      - stargates/finalizers
    verbs:
      - update
  - apiGroups:
      - stargate.k8ssandra.io
    resources:
      - stargates/status
    verbs:
      - get
      - patch
      - update
