{{- if semverCompare ">=1.24-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8ssandra-common.serviceAccountName" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "k8ssandra-common.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}