apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8ssandra-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "k8ssandra-common.labels" . | indent 8 }}
    spec:
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName:  {{ include "k8ssandra-common.serviceAccountName" . }}
      containers:
      - args:
        - --leader-elect
        command:
          - /manager
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: {{ include "k8ssandra-common.flattenedImage" .Values.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: medusa-operator
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
      terminationGracePeriodSeconds: 10
