apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "k8ssandra-common.fullname" . }}
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - list
      - watch
  - apiGroups:
      - cassandra.datastax.com
    resources:
      - cassandradatacenters
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cassandra.k8ssandra.io
    resources:
      - cassandrabackups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cassandra.k8ssandra.io
    resources:
      - cassandrabackups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cassandra.k8ssandra.io
    resources:
      - cassandrarebackups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cassandra.k8ssandra.io
    resources:
      - cassandrarestores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cassandra.k8ssandra.io
    resources:
      - cassandrarestores/status
    verbs:
      - get
      - patch
      - update