{{- $storageTypes :=  list "s3" "s3_compatible" "google_storage" "azure_blobs" "local" -}}

{{- if .Values.medusa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "medusa.configMapName" . }}
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
data:
  medusa.ini: |-
    [cassandra]
    # The start and stop commands are not applicable in k8s.
    stop_cmd = /etc/init.d/cassandra stop
    start_cmd = /etc/init.d/cassandra start
  {{- if not .Values.cassandra.auth.enabled }}
    cql_username = cassandra
    cql_password = cassandra
  {{- end}}
    check_running = nodetool version

    [storage]
  {{- if (not (has .Values.medusa.storage $storageTypes)) }}
    {{ fail (print "Accepted storage type values are " $storageTypes) }}
  {{- end }}
    storage_provider = {{ .Values.medusa.storage }}
  {{- range $key, $value := .Values.medusa.storage_properties }}
    {{ $key }} = {{ $value }}
  {{- end }}
  {{- if eq "local" .Values.medusa.storage }}
    base_path = /mnt/backups
    {{- /*
      Medusa requires the bucket_name property to be set even when using local storage.
      See https://github.com/thelastpickle/cassandra-medusa/issues/299.
    */ -}}
    {{ nindent 4 "" }}bucket_name = "local"
  {{- else }}
    bucket_name = {{ .Values.medusa.bucketName }}
  {{- end }}
  {{- if or (eq .Values.medusa.storage "s3") (eq .Values.medusa.storage "s3_compatible") }}
    key_file = /etc/medusa-secrets/medusa_s3_credentials
  {{- else if (eq .Values.medusa.storage "google_storage") }}
    key_file = /etc/medusa-secrets/medusa_gcp_key.json
  {{- else if (eq .Values.medusa.storage "azure_blobs") }}
    key_file = /etc/medusa-secrets/medusa_azure_credentials.json
  {{- end }}
{{- if .Values.medusa.multiTenant }}
    prefix = {{ .Values.clusterName }}.{{ .Release.Namespace }}
{{- end }}

    [grpc]
    enabled = 1

    [kubernetes]
    cassandra_url = http://127.0.0.1:8080/api/v0/ops/node/snapshots
    use_mgmt_api = 1
    enabled = 1

    [logging]
    level = DEBUG
  {{- end }}
