---
name: Builder Cleaner
on:
  push:
    branches:
     - main
    paths:
      - 'pkg/**'
      - 'cmd/**'

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.15
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login docker.io --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    - name: Build and push image
      if: github.ref == 'refs/heads/main'
      run: make cleaner-docker-build cleaner-docker-push
