name: License Scanning
on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1
