name: Dependency and License Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_PUSH_ONLY_API_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Debug
        run: echo "FOSSA_API_KEY: $FOSSA_API_KEY"
      - name: Install Fossa CLI
        run: curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - name: Initialize project
        run: fossa init
      - name: Scan for dependencies and licenses
        run: fossa analyze
