name: Publish docs.k8ssandra.io

on:
  push:
    tags:
      - 'docs-v[0-9].[0-9]+.[0-9]+'

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
    - uses: actions/checkout@v2
      name: Checkout code w/ submodules
      with:
        submodules: recursive
    - uses: google-github-actions/setup-gcloud@master
      name: Setup gcloud
      with:
        project_id: ${{ secrets.GCP_DOCS_PROD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_DOCS_PROD_SA_KEY }}
        export_default_credentials: true
    - uses: actions/setup-node@v2
      name: Setup Node
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run clean
    - run: npm run build:production
    - run: npm run deploy:production
    - name: Purge CDN Cache
      env:
        ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        BEARER_TOKEN: ${{ secrets.CF_BEARER_TOKEN }}
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/purge_cache" \
          -H "Authorization: Bearer ${BEARER_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
    - name: Ping Google with Sitemap
      run: |
        curl -X GET -L "http://www.google.com/ping?sitemap=https://k8ssandra.io/sitemap.xml"
